### ISSUE TITLE
Thanks For Order flow 

### ISSUE THREAD

**Issue by krishnam7** [AndreaFerrante/Orderflow#1]
Dear Andrea Ferrante

Thanks for the Order flow Volume profile update in python. I was searching for a know-how technical way to implement the order flow, Volume Profile, Market Profile, and Imbalance for trading. it helped me a lot.

Can you create a Market profile and imbalance in order flow?

Thanks once again.

Krishna Mekala

**Comment by AndreaFerrante** [comment]
Thank you for your request.
Have in mind that this package is not aimed in providing trading signals !
I am just fascinated in analyzing data and I personally do not trade.

**Comment by krishnam7** [comment]
Thanks for the reply.

can you guide how to use it for trading signals?

**Comment by AndreaFerrante** [comment]
I am no trader dear Krishnam, so I think I am not the correct person to guide since I do not trade any instrument.
Again, as a data scientist,  I am just courious towards the impressive amount of data is out there.
